# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.Qt import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(815, 771)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 971, 91))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std")
        font.setPointSize(48)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushbutton_choosepic = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_choosepic.setGeometry(QtCore.QRect(310, 160, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushbutton_choosepic.setFont(font)
        self.pushbutton_choosepic.setIconSize(QtCore.QSize(30, 30))
        self.pushbutton_choosepic.setObjectName("pushbutton_choosepic")
        self.pushbutton_process = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_process.setGeometry(QtCore.QRect(510, 160, 117, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushbutton_process.setFont(font)
        self.pushbutton_process.setIconSize(QtCore.QSize(30, 30))
        self.pushbutton_process.setObjectName("pushbutton_process")
        # 创建菜单
        self.menu = QMenu()
        # 创建action并添加到菜单中
        self.action1 = QAction(QIcon("menu.ico"), "所有轮廓", self.menu)
        self.action2 = QAction(QIcon("menu.ico"), "细节", self.menu)

        self.pushbutton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_save.setGeometry(QtCore.QRect(810, 160, 117, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushbutton_save.setFont(font)
        self.pushbutton_save.setIconSize(QtCore.QSize(30, 30))
        self.pushbutton_save.setObjectName("pushbutton_save")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 210, 1011, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(550, 250, 391, 59))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 250, 541, 59))
        self.label_3.setObjectName("label_3")
        self.label_img = QtWidgets.QLabel(self.centralwidget)
        self.label_img.setEnabled(True)
        self.label_img.setGeometry(QtCore.QRect(60, 320, 441, 511))
        self.label_img.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_img.setFrameShape(QtWidgets.QFrame.Box)
        self.label_img.setObjectName("label_img")

        self.label_processimg = QtWidgets.QLabel(self.centralwidget)
        self.label_processimg.setEnabled(True)
        self.label_processimg.setGeometry(QtCore.QRect(530, 320, 441, 511))
        self.label_processimg.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_processimg.setFrameShape(QtWidgets.QFrame.Box)
        self.label_processimg.setObjectName("label_processimg")

        self.label_imgpath = QtWidgets.QLabel(self.centralwidget)
        self.label_imgpath.setGeometry(QtCore.QRect(160, 130, 421, 31))
        self.label_imgpath.setObjectName("label_imgpath")
        self.pushbutton_slideview = QtWidgets.QPushButton(self.centralwidget)
        self.pushbutton_slideview.setEnabled(True)
        self.pushbutton_slideview.setGeometry(QtCore.QRect(660, 160, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.pushbutton_slideview.setFont(font)
        self.pushbutton_slideview.setObjectName("pushbutton_slideview")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 815, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.action1.triggered.connect(lambda: print("点击了 action1"))
        self.action2.triggered.connect(lambda: print("点击了 action2"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow",
                                      "<html><head/><body><p><span style=\" color:#ff5500;\">雕刻图像轮廓处理</span></p></body></html>"))
        self.pushbutton_choosepic.setText(_translate("MainWindow", "选择图片"))
        self.pushbutton_process.setText(_translate("MainWindow", "处理"))
        self.menu.addActions([self.action1,self.action2])

        self.pushbutton_process.setMenu(self.menu)

        self.pushbutton_save.setText(_translate("MainWindow", "保存"))
        self.label_2.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">轮廓图</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow",
                                        "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">原图像</span></p></body></html>"))
        self.label_img.setText(_translate("MainWindow", "待载入图片..."))
        self.label_processimg.setText(_translate("MainWindow", "待处理图片..."))
        self.label_imgpath.setText(_translate("MainWindow", "未选择图片..."))
        self.pushbutton_slideview.setText(_translate("MainWindow", "优化"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    formObj = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(formObj)
    formObj.show()

    sys.exit(app.exec_())
